#!/bin/sh

wmname LG3D

# LAUNCHERS

# pkill -USR1 -x sxhkd || pgrep -x sxhkd > /dev/null || sxhkd -c ~/.config/sxhkd/sxhkdrc ~/.config/sxhkd/sxhkdrc-bspwm &

# picom --config ~/.config/picom/picom.conf &
picom &
# xcompmgr &


# Single monitor
# bspc monitor -d I II III IV V
# bspc monitor -d     
# bspc monitor -d          
# bspc monitor -d          

# bspc monitor -d           1h 30m 15m 5m 1m B

# Dual monitor
# find out names with arandr or xrandr
# bspc monitor DP-4 -d  1 2 3 4 5 6 7 8 9 10
# bspc monitor eDP-1-1 -d 1 2 3 4 5 6 7 8 9 10

# Dual monitor
# bspc monitor eDP-1 -d 1 2 3 4
bspc monitor -d     
# bspc monitor DP-4 -d     


# BSPWM configuration
#bspc config border_radius       8
bspc config border_width        2
bspc config window_gap          4

bspc config top_padding      32

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

# BSPWM coloring
bspc config normal_border_color		"#4c566a"
bspc config active_border_color		"#1e1e1e"
bspc config focused_border_color	"#5e81ac"
bspc config presel_feedback_color	"#5e81ac"
bspc config urgent_border_color 	"#dd2727"

bspc rule -a plasmashell state=floating border=off sticky=off center=off
bspc rule -a krunner state=floating border=off

bspc rule -a rofi state=floating sticky=on
bspc rule -a PowerManagement state=floating sticky=on

# bspc rule -a systemsettings desktop='^10'
# bspc rule -a QuiteRSS desktop='^7'
# bspc rule -a KeePassXC desktop='^8'
# bspc rule -a GitAhead desktop='^6'
# bspc rule -a dolphin desktop='^3'


# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

~/.config/bspwm/autostart.sh &

#~ $HOME/.config/polybar/launch.sh &
