general.live_config_reload = true

[bell]
animation = "EaseOutExpo"
duration = 0

[colors.primary]
background = "0x0d1117"
foreground = "0xc9d1d9"

[colors.cursor]
text = "0x0d1117"
cursor = "0xc9d1d9"

[colors.normal]
black = "0x484f58"
red = "0xff7b72"
green = "0x58a6ff"
yellow = "0xd29922"
blue = "0x58a6ff"
magenta = "0xbc8cff"
cyan = "0x39c5cf"
white = "0xb1bac4"

[colors.bright]
black = "0x6e7681"
red = "0xffa198"
green = "0x79c0ff"
yellow = "0xe3b341"
blue = "0x79c0ff"
magenta = "0xbc8cff"
cyan = "0x39c5cf"
white = "0xb1bac4"

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = false

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
decorations = "full"
dynamic_title = true
startup_mode = "Maximized"

[window.padding]
x = 10
y = 10
